module.exports = {
  blacklist: [
    'ODC',
    'MPL',
    'GNU',
    'GPL',
    'Mechanical',
    'OCLC',
    'RPSL',
    'NGPL',
    'RPL',
    'PPL',
    'EPL',
    'OSL',
    'Ms-RL',
    'ODbL',
    'MTS',
  ],
  whitelist: [
    'eslint-plugin-jsx-a11y',
    'eslint-plugin-sonarjs',
    'webpack-dev-server',
    'extract-css-chunks-webpack-plugin',
    'wowjs',
    'isotope-layout',
    'sharer.js',
    'gulp-bump',
    'scrollreveal',
    'stylint',
  ],
};
